object Versions {

    const val coreKtx = "1.9.0"
    const val appcompat = "1.6.1"
    const val lifeCycleRunTimeKtx = "2.6.2"
    const val activityCompose = "1.8.2"
    const val activityBom = "2023.08.00"
    const val navigationCompose = "2.7.6"
    const val junit = "4.13.2"
    const val lifecycleViewModelKtx = "2.6.2"
    const val material = "1.9.0"
    const val hilt = "2.48"
    const val hiltCompiler = "1.1.0"
    const val hiltNavigationCompose = "1.1.0"
    const val retrofit = "2.9.0"
    const val okHttp = "5.0.0-alpha.2"
    const val gsonConverter = "2.9.0"
    const val moshi = "1.13.0"
    const val moshiKotlin = "1.14.0"
    const val moshiConvertor = "2.9.0"
    const val loggingInterceptor = "4.8.1"
    const val coroutine = "1.7.3"
    const val splashScreen = "1.0.1"
}